Django Project/movie_application/winerama/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[

	url(r'^create/', views.create,name='create'),
	url(r'^$', views.home,name='home'),
	url(r'^(?P<pk>[0-9]+)/upvote', views.upvote,name='upvote'),
	url(r'^(?P<pk>[0-9]+)/downvote', views.downvote,name='downvote'),
	url(r'^user/(?P<pk>[0-9]+)/', views.userposts,name='userposts'),
]

Django Project/movie_application/winerama/reviews/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    url(r'^wine/add_search/$', views.add_search, name='add_search'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    # ex: /review/user - get reviews for the user passed in the url
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    # ex: /recommendation - get wine recommendations for the logged user
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^wine/shopping_cart/$', views.shopping_cart, name='shopping_cart'),
    url(r'^wine/add_movie/(?P<wine_id>[0-9]+)/$', views.add_movie, name='add_movie'),
    url(r'^wine/recently_bought/(?P<wine_id>[0-9]+)/$', views.recently_bought, name='recently_bought'),
    url(r'^wine/already_bought/(?P<wine_id>[0-9]+)/$', views.already_bought, name='already_bought'),
    url(r'^wine/already_added_to_cart/(?P<wine_id>[0-9]+)/$', views.already_added_to_cart, name='already_added_to_cart'),
    url(r'^wine/checkout/$', views.checkout, name='checkout'),
    url(r'^wine/my_movies/$', views.my_movies, name='my_movies'),
    url(r'^wine/remove_movie/(?P<wine_id>[0-9]+)/$', views.remove_movie, name='remove_movie'),
]

Django Project/movie_application/winerama/winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #url(r'^$', include('reviews.urls', namespace="reviews_home")),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
    
    #accounts urls
    url(r'^forum/', include('accounts.urls', namespace="forum")),
    #posts url
    url(r'^posts/', include('posts.urls', namespace="posts")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django Project/movie_application/winerama/reviews/models.py
from django.db import models
from django.contrib.auth.models import User
import numpy as np


class Wine(models.Model):
    name = models.CharField(max_length=200)
    #price = models.FloatField()
    
    def average_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        return np.mean(all_ratings)
        
    def __string__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    wine = models.ForeignKey(Wine)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)


class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])


class Bought(models.Model):
    user_name = models.CharField(max_length=100)
    wine = models.ForeignKey(Wine)
    pub_date = models.DateTimeField('date bought')



class FinalBuy(models.Model):
    user_name=models.CharField(max_length=100)
    tranno=models.IntegerField(default=0)
    wine=models.ForeignKey(Wine)
    buy_date=models.DateTimeField('date bought')

Django Project/movie_application/winerama/reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }


class SearchForm(ModelForm):
	class Meta:
		model = Review
		fields = ['comment']
		widgets ={
			'comment': Textarea(attrs={'cols':15, 'rows':1}),
		}

Django Project/movie_application/winerama/reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .models import Review, Wine, Cluster,Bought,FinalBuy
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm, SearchForm
from .suggestions import update_clusters
import datetime
from .recommends import movie_suggestion
import pandas as pd
import sqlite3
from .apriori import func1

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')[300:700]
    context = {'wine_list':wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})

def add_search(request): 
   
    if request.method == 'POST':
        if request.POST.get('numero', False):
            m = request.POST['numero']    
            print ("My Number is ", m )
            
            wine_list = Wine.objects.filter(name__contains=m)
            context = {'wine_list':wine_list}
            return render(request, 'reviews/searched_movies.html', context)

    
    return render(request, 'reviews/searched_movies.html')



@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,))) # after adding the review, it redirects to the same page again
    
   # return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'reviews/user_review_list.html', context)


@login_required
def user_recommendation_list(request):
    x = movie_suggestion(request.user.username)
    # wine_list = list(Wine.objects.filter(id__in=x))    
    wine_list = list(Wine.objects.filter(name__in=x))
    print("heretheycome", wine_list)
    # wine_list = x
    return render(request, 'reviews/user_recommendation_list.html', 
        {'username': request.user.username,'wine_list': wine_list}
    )
    
 


@login_required
def shopping_cart(request):
    cnx = sqlite3.connect(r'C:\Users\sambhav\Desktop\winerama_2\winerama\db.sqlite3')
    df = pd.read_sql_query("select * from reviews_bought", cnx)
    user_name1 = request.user.username
    ad=[]
    for i in range(len(df)):
        if df['user_name'][i]== user_name1:
            wine_id=df['wine_id'][i]
            wine=Wine.objects.get(pk=wine_id)
            ad.append(wine)
    return render(request,'reviews/shopping_cart.html',{'movies':ad})    

@login_required
def add_movie(request, wine_id):
    cnx = sqlite3.connect(r'C:\Users\sambhav\Desktop\winerama_2\winerama\db.sqlite3')
    df = pd.read_sql_query("select * from reviews_bought", cnx)
    df1= pd.read_sql_query("select * from reviews_finalbuy",cnx)
    user_name1 = request.user.username
    t=[]
    t1=[]
    for i in range(len(df)):
        if df['user_name'][i]== user_name1:
            t.append(df['wine_id'][i])
    for i in range(len(df1)):
        if df1['user_name'][i]== user_name1:
            t1.append(df1['wine_id'][i])
    if int(wine_id) in t:
        return HttpResponseRedirect(reverse('reviews:already_added_to_cart', args=(wine_id,)))
    elif int(wine_id) in t1:
        return HttpResponseRedirect(reverse('reviews:already_bought', args=(wine_id,)))
    else:
        wine = get_object_or_404(Wine, pk=wine_id)
        buy = Bought()
        buy.wine = wine
        buy.user_name = user_name1
        buy.pub_date = datetime.datetime.now()
        buy.save()
        return HttpResponseRedirect(reverse('reviews:recently_bought', args=(wine.id,))) 



@login_required
def recently_bought(request,wine_id):
    wine=Wine.objects.get(pk=wine_id)
    res=func1(int(wine_id))
    r=len(res)
#    print(r)
 #   print(r-1)
    ans=[]
    ans1=[]
    if bool(res)==True:
        for item in res[r-1]:
            ans.append(item)
        for item in ans:
            wine1=Wine.objects.get(pk=item)
            ans1.append(wine1)
    return render(request,'reviews/recently_bought.html',{'wine':wine,'res':ans1}) 

@login_required
def already_bought(request,wine_id):
    wine=Wine.objects.get(pk=wine_id)
    return render(request,'reviews/already_bought.html',{'wine':wine}) 


@login_required
def already_added_to_cart(request,wine_id):
    wine=Wine.objects.get(pk=wine_id)
    return render(request,'reviews/already_added_to_cart.html',{'wine':wine}) 



@login_required
def checkout(request):
    cnx = sqlite3.connect(r'C:\Users\sambhav\Desktop\winerama_2\winerama\db.sqlite3')
    df = pd.read_sql_query("select * from reviews_bought", cnx)
    user_name1 = request.user.username
    t=[]
    tranno1=0
    df1=pd.read_sql_query("select * from reviews_finalbuy",cnx)
    for i in range(len(df1)):
        tranno1=df1['tranno'][i]
    for i in range(len(df)):
        if df['user_name'][i]==user_name1:
            wid=df['wine_id'][i]
            pid=df['id'][i]
            wine = get_object_or_404(Wine, pk=wid)
            t.append(df['wine_id'][i])
            buy=FinalBuy()
            buy.wine=wine
            buy.user_name=user_name1
            buy.buy_date=datetime.datetime.now()
            buy.tranno=tranno1+1
            buy.save()
            Bought.objects.filter(id=pid).delete()
    return render(request,'reviews/checkout.html') 


@login_required
def my_movies(request):
    cnx = sqlite3.connect(r'C:\Users\sambhav\Desktop\winerama_2\winerama\db.sqlite3')
    df = pd.read_sql_query("select * from reviews_finalbuy", cnx)
    user_name1 = request.user.username
    ad=[]
    for i in range(len(df)):
        if df['user_name'][i]== user_name1:
            wine_id=df['wine_id'][i]
            wine=Wine.objects.get(pk=wine_id)
            ad.append(wine)
    return render(request,'reviews/my_movies.html',{'movies':ad})    

@login_required
def remove_movie(request,wine_id):
    cnx = sqlite3.connect(r'C:\Users\sambhav\Desktop\winerama_2\winerama\db.sqlite3')
    df=pd.read_sql_query("select * from reviews_bought",cnx)
    user_name1=request.user.username
    for i in range(len(df)):
        if df['user_name'][i]==user_name1:
            if df['wine_id'][i]==int(wine_id):
                pid=df['id'][i]
                Bought.objects.filter(id=pid).delete()
    df=pd.read_sql_query("select * from reviews_bought",cnx)
    ad=[]
    for i in range(len(df)):
        if df['user_name'][i]== user_name1:
            wine_id=df['wine_id'][i]
            wine=Wine.objects.get(pk=wine_id)
            ad.append(wine)
    return render(request,'reviews/shopping_cart.html',{'movies':ad})    

Django Project/movie_application/winerama/reviews/templates/reviews/already_added_to_cart.html
{% extends 'base.html' %}


{% block title %}
<h2>You have already added this movie to your Cart! </h2>
{% endblock %}

{% block content %}
<h2>Check out the movies Arena for more! </h2>


{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/already_bought.html
{% extends 'base.html' %}


{% block title %}
<h2>You have already bought this movie! </h2>
{% endblock %}

{% block content %}
<h2>Check out the movies Arena for more! </h2>


{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/checkout.html
{% extends 'base.html' %}


{% block title %}
<h2>Thank You for Using Our Service!</h2>
{% endblock %}

{% block content %}
<h3>Continue Shopping!!</h3>
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/my_movies.html
{% extends 'base.html' %}


{% block title %}
<h2>Welcome </h2>
{% endblock %}

{% block content %}
{%if movies%}
<h2>Following movies have been rented by you </h2>
{%for wine in movies%}
<h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
<br />
{%endfor%}
{% else %}
<h2>No movies have been rented by you </h2>
{% endif %}
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/recently_bought.html
{% extends 'base.html' %}


{% block title %}
<h2>Added To Cart!! </h2>
{% endblock %}

{% block content %}
<h2>You added {{wine.name}} to Cart</h2>
{% if wine.review_set.all %}
<h3>What do others say about this movie??</h3>
<div class="row">
    {% for review in wine.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>Be the first one to review!!</p>
{% endif %}
{% if res %}
<h3>Items frequently bought together</h3>
<h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
{%for wine in res%}
<h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
{% endfor %}
{% endif %}

{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}





{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/searched_movies.html
{% extends 'base.html' %}

{% block title %}
<h2>We found the following results</h2>
{% endblock %}

{% block content %}
{% if wine_list %}
<div class="row">
    {% for wine in wine_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
        <h5>{{ wine.review_set.count }} reviews</h5>
        <h5>{{ wine.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No wines are available.</p>
{% endif %}
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/shopping_cart.html
{% extends 'base.html' %}


{% block title %}
<h2>Welcome </h2>
{% endblock %}

{% block content %}
{%if movies%}
<h2>Following movies have been added to the cart </h2>
{%for wine in movies%}
<h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
<form action ="{% url 'reviews:remove_movie'  wine.id%}" >
<button type="submit" class="btn btn-danger" aria-label="Left Align">
 Remove
</button>
</form>
<br />
{%endfor%}
<form action ="{% url 'reviews:checkout' %}" >
<button type="submit" class="btn btn-success btn-lg" aria-label="Left Align">
 CheckOut!
</button>
</form>
{% else %}
<h2>No movies in cart </h2>
{% endif %}
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/user_recommendation_list.html
{% extends 'reviews/wine_list.html' %}

{% block title %}
<h2>Movie suggestions for {{ username }}</h2>
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2b style="color:#EE220D">{{ wine.name }}</h2b>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div class="row">
    {% for review in wine.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="row">
<form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
            <div class="col-xs-6 col-lg-10">
            {% buttons %}
            <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit Review
            </button>
            {% endbuttons %}
        </div>
</form>
<form action="{% url 'reviews:add_movie' wine.id %}" >
            {% buttons %}
            <button type="submit" class="btn btn-success">
            {% bootstrap_icon "cd" %} Add to Cart
            </button>
            {% endbuttons %}
</form>
</div>
{% endblock %}

Django Project/movie_application/winerama/reviews/templates/reviews/wine_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Movie list</h2>
{% endblock %}

{% block content %}
{% if wine_list %}
<div class="row">
    {% for wine in wine_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:wine_detail' wine.id %}">
        {{ wine.name }}
        </a></h4>
        <h5>{{ wine.review_set.count }} reviews</h5>
        <h5>{{ wine.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No Movies are available.</p>
{% endif %}
{% endblock %}