Django Project/movie_application/winerama/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^signup/', views.signup,name='signup'),
	url(r'^login/', views.loginview,name='login'),
	url(r'^logout/', views.logoutview,name='logout'),
]

Django Project/movie_application/winerama/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[

	url(r'^create/', views.create,name='create'),
	url(r'^$', views.home,name='home'),
	url(r'^(?P<pk>[0-9]+)/upvote', views.upvote,name='upvote'),
	url(r'^(?P<pk>[0-9]+)/downvote', views.downvote,name='downvote'),
	url(r'^user/(?P<pk>[0-9]+)/', views.userposts,name='userposts'),
]

Django Project/movie_application/winerama/reviews/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /wine/
    url(r'^wine$', views.wine_list, name='wine_list'),
    url(r'^wine/add_search/$', views.add_search, name='add_search'),
    # ex: /wine/5/
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    # ex: /review/user - get reviews for the user passed in the url
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    # ex: /recommendation - get wine recommendations for the logged user
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    url(r'^wine/shopping_cart/$', views.shopping_cart, name='shopping_cart'),
    url(r'^wine/add_movie/(?P<wine_id>[0-9]+)/$', views.add_movie, name='add_movie'),
    url(r'^wine/recently_bought/(?P<wine_id>[0-9]+)/$', views.recently_bought, name='recently_bought'),
    url(r'^wine/already_bought/(?P<wine_id>[0-9]+)/$', views.already_bought, name='already_bought'),
    url(r'^wine/already_added_to_cart/(?P<wine_id>[0-9]+)/$', views.already_added_to_cart, name='already_added_to_cart'),
    url(r'^wine/checkout/$', views.checkout, name='checkout'),
    url(r'^wine/my_movies/$', views.my_movies, name='my_movies'),
    url(r'^wine/remove_movie/(?P<wine_id>[0-9]+)/$', views.remove_movie, name='remove_movie'),
]

Django Project/movie_application/winerama/winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #url(r'^$', include('reviews.urls', namespace="reviews_home")),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
    
    #accounts urls
    url(r'^forum/', include('accounts.urls', namespace="forum")),
    #posts url
    url(r'^posts/', include('posts.urls', namespace="posts")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django Project/movie_application/winerama/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<body class="body" style="background-color:#FFFFFF">
<div class="container-fluid">
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">MovieArena</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:wine_list' %}">Movie list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
                <li><a href="{% url 'posts:home' %}">Forum</a></li>
        <form action="{% url 'reviews:add_search' %}" method="post" class="navbar-form navbar-left">
     {% csrf_token %}
        
          <input type="text" class="form-control" placeholder="Search" name="numero"/>
        
        <button type="submit" class="btn btn-default">Submit</button>
 </form>
                

            </ul>
    <form action="{% url 'reviews:shopping_cart' %}" method="post" class="navbar-form navbar-right">
    {% csrf_token %}

            <ul class="nav navbar-nav navbar-left">
                <li><button type="submit" class="btn btn-default btn-lg" >
                    <span class="glyphicon glyphicon-shopping-cart" ></span>
                    </button>   
                </li>
            </ul>
    </form>

            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'reviews:user_recommendation_list' %}">Movie suggestions</a></li>
                
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>

        <form action="{% url 'reviews:my_movies' %}" method="post" class="navbar-form navbar-right">
        {% csrf_token %}

                <ul class="nav navbar-nav navbar-left">
                    <li><button type="submit" class="btn btn-success btn-lg" >
                        My Movies!
                        </button>   
                    </li>
                </ul>
        </form>




                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                
                {% endif %}
            </ul>
        </div>
    </nav>

<!--{%load static%}
<img src="{% static 'Cinema.jpg' %}" class="img-responsive center-block" style="max-height:300px"/>
-->
    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>





{% endblock %}

Django Project/movie_application/winerama/templates/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Forum</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:home'%}">
        MoviesDiscuss
      </a>
    </div>
       <div class="collapse navbar-collapse" id="mynav">
        <ul class="nav navbar-nav">
        <li><a href="{% url 'reviews:review_list' %}">MovieArena</a></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a href="#" onclick="document.getElementById('logout').submit()">Logout</a></li>
      <form id="logout" method = "POST" action="{%url 'forum:logout' %}">
		{% csrf_token %}
		<input type="hidden"/>
	  </form>
      {% else %}
      <li><a href="{% url 'forum:signup' %}">SignUp</a></li>
      <li><a href="{% url 'forum:login' %}">Login</a></li>
      {% endif %}
      </ul>
      </div>
  </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>