Django Project/movie_application/winerama/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns=[

	url(r'^create/', views.create,name='create'),
	url(r'^$', views.home,name='home'),
	url(r'^(?P<pk>[0-9]+)/upvote', views.upvote,name='upvote'),
	url(r'^(?P<pk>[0-9]+)/downvote', views.downvote,name='downvote'),
	url(r'^user/(?P<pk>[0-9]+)/', views.userposts,name='userposts'),
]

Django Project/movie_application/winerama/winerama/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #url(r'^$', include('reviews.urls', namespace="reviews_home")),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
    
    #accounts urls
    url(r'^forum/', include('accounts.urls', namespace="forum")),
    #posts url
    url(r'^posts/', include('posts.urls', namespace="posts")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django Project/movie_application/winerama/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
	title=models.CharField(max_length=200)
	url=models.TextField()
	pub_date=models.DateTimeField()
	author=models.ForeignKey(User)
	votes_total=models.IntegerField(default=0)

	def pub_date_pretty(self):
		return self.pub_date.strftime('%b %d %Y')

Django Project/movie_application/winerama/posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .import models
from django.contrib.auth.models import User

# Create your views here.


@login_required
def create(request):
	if request.method=='POST':
		if request.POST['title'] and request.POST['url']:
			post=models.Post()
			post.title=request.POST['title']
			if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
				post.url=request.POST['url']
			else:
				post.url='http://'+request.POST['url']
			post.pub_date=timezone.datetime.now()
			post.author=request.user
			post.save() 
			return redirect('posts:home')
		else:
			return render(request,'posts/create.html',{'error':'ERROR:You must include a title and a URL'})
	else:
		return render(request,'posts/create.html')


def home(request):
	posts=models.Post.objects.order_by('-votes_total')
	return render(request,'posts/home.html',{'posts':posts})

def upvote(request,pk):
	if request.method=='POST':
		post=models.Post.objects.get(pk=pk)
		post.votes_total+=1
		post.save()
		return redirect('posts:home')

def downvote(request,pk):
	if request.method=='POST':
		post=models.Post.objects.get(pk=pk)
		post.votes_total-=1
		post.save()
		return redirect('posts:home')

def userposts(request,pk):
	posts=models.Post.objects.filter(author__id=pk).order_by('-votes_total')
	author=User.objects.get(pk=pk)
	return render(request,'posts/userposts.html',{'posts':posts,'author':author})

Django Project/movie_application/winerama/posts/templates/posts/create.html
{% extends 'base1.html' %}
{% block content %}



<h1>New Post</h1>
{% if error %}
{{error}}
<br/>
<br/>
{% endif %}
<form method = "POST" action="{%url 'posts:create'%}">
{% csrf_token %}
Title:<br/>
<input type="text" name="title" />
<br/>
URL:
<br/>
<input type="text" name="url" />
<br/>
<br/>
<input class="btn btn-primary" type="Submit" value="Post"/>
</form>

{% endblock %}

Django Project/movie_application/winerama/posts/templates/posts/home.html
{% extends 'base1.html' %}
{% block content %}


<h1>The front page of the movies!</h1>
<a class="btn btn-primary" href="{% url 'posts:create' %}">
New Post</a>

<br/>
<br/>

{% for post in posts.all %}

<table>
<tr>
<td style="padding-right: 20px;"> <a href="#" onclick="document.getElementById('upvote{{post.id}}').submit()"> <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span> </a><br/>{{post.votes_total}} <br/> <a href="#" onclick="document.getElementById('downvote{{post.id}}').submit()"> <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true">
</span> </a> </td>
<td><a href="{{post.url}}">{{post.title}}</a>
<br/>
{{post.pub_date_pretty}} by <a href="{% url 'posts:userposts' post.author.id %}">{{post.author.username}}</a>
<br/>
</td>
</tr>
<br/>
</table>


<form id="upvote{{post.id}}" method = "POST" action="{%url 'posts:upvote' post.id%}">
{% csrf_token %}
<input type="hidden" />
</form>


<form id= "downvote{{post.id}}" method = "POST"  action="{%url 'posts:downvote' post.id%}">
{% csrf_token %}
<input type="hidden"/>
</form>


{% endfor %}


{% endblock %}

Django Project/movie_application/winerama/posts/templates/posts/userposts.html
{% extends 'base1.html' %}
{% block content %}


<h1>All Posts By {{author.username}}</h1>

<br/>

{% for post in posts.all %}

<table>
<tr>
<td style="padding-right: 20px;"> <a href="#" onclick="document.getElementById('upvote{{post.id}}').submit()"> <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span> </a><br/>{{post.votes_total}} <br/> <a href="#" onclick="document.getElementById('downvote{{post.id}}').submit()"> <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true">
</span> </a> </td>
<td><a href="{{post.url}}">{{post.title}}</a>
<br/>
{{post.pub_date_pretty}} by <a href="{% url 'posts:userposts' post.author.id %}">{{post.author.username}}</a>
<br/>
</td>
</tr>
<br/>
</table>


<form id="upvote{{post.id}}" method = "POST" action="{%url 'posts:upvote' post.id%}">
{% csrf_token %}
<input type="hidden" />
</form>


<form id= "downvote{{post.id}}" method = "POST"  action="{%url 'posts:downvote' post.id%}">
{% csrf_token %}
<input type="hidden"/>
</form>


{% endfor %}


{% endblock %}